# Generated by Django 4.2.1 on 2023-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('AM', 'Admin'), ('AT', 'Author'), ('RR', 'Reader')], default='RR', max_length=2, verbose_name='User Role'),
        ),
    ]
