# Generated by Django 4.2.1 on 2023-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('AM', 'Admin'), ('AT', 'Author'), ('RR', 'Reader')], default='AT', max_length=2, verbose_name='User Role'),
        ),
    ]
